export const projects=[
 {tag:"Voluntariado",title:"Distribuição de Alimentos",text:"Campanha contínua de arrecadação e distribuição de alimentos para famílias da comunidade.",icon:"📦"},
 {tag:"Educação",title:"Projeto Educação",text:"Oficinas e atividades educacionais para crianças e adolescentes.",icon:"📚"},
 {tag:"Meio Ambiente",title:"Comunidade Sustentável",text:"Ações de preservação e conscientização ambiental.",icon:"🌱"}
];
export function projectCards(){return projects.map(p=>`<article class="card"><div class="card-visual" aria-hidden="true">${p.icon}</div><div class="badges"><span class="badge">${p.tag}</span></div><h3>${p.title}</h3><p>${p.text}</p></article>`).join("")}
export const views={
 home:()=>`<section class="hero"><div class="hero-inner"><h1>Conectando pessoas para transformar vidas</h1><p>A Nexus é uma organização do terceiro setor que desenvolve projetos sociais por meio do voluntariado, da educação e da solidariedade.</p><div class="actions"><a class="btn" href="#/projetos">Conheça nossos projetos</a><a class="btn secondary" href="#/voluntariado">Seja voluntário</a></div></div></section><section class="section"><div class="badges"><span class="badge">Voluntariado</span><span class="badge">Projeto Ativo</span><span class="badge">Doações</span><span class="badge">Comunidade</span></div><div class="alert info"><strong>Atenção!</strong> As doações podem ser entregues em nosso centro de apoio de segunda a sexta, das 9h às 17h.</div><h2>Nossos projetos</h2><div class="cards">${projectCards()}</div></section>`,
 projetos:()=>`<section class="section"><h1>Projetos</h1><p>Iniciativas que conectam pessoas, oportunidades e comunidades.</p><div class="cards">${projectCards()}</div></section>`,
 doacoes:()=>`<section class="section"><h1>Doações</h1><p>Seu apoio gera novas possibilidades. A Nexus organiza campanhas de arrecadação para apoiar ações comunitárias.</p><div class="alert info">Consulte os projetos ativos e contribua de acordo com as necessidades apresentadas.</div></section>`,
 sobre:()=>`<section class="section"><h1>Sobre a Nexus</h1><p>A Nexus — Conexões que Transformam é uma proposta de organização do terceiro setor voltada à conexão entre voluntários, projetos sociais e comunidades.</p><h2>Missão</h2><p>Unir pessoas, oportunidades e comunidades para um futuro mais justo e solidário.</p></section>`,
 contato:()=>`<section class="section"><h1>Contato</h1><form class="form" id="contact-form" novalidate><div class="field"><label for="contact-name">Nome *</label><input id="contact-name" name="name" required autocomplete="name"><div class="error"></div></div><div class="field"><label for="contact-email">E-mail *</label><input id="contact-email" name="email" type="email" required autocomplete="email"><div class="error"></div></div><div class="field"><label for="message">Mensagem *</label><textarea id="message" name="message" required rows="5"></textarea><div class="error"></div></div><button class="btn">Enviar</button></form></section>`,
 voluntariado:()=>`<section class="section"><h1>Seja voluntário</h1><p>Pessoas que fazem a diferença todos os dias.</p><form class="form" id="volunteer-form" novalidate><div class="field"><label for="name">Nome completo *</label><input id="name" name="name" required minlength="3" autocomplete="name"><div class="error"></div></div><div class="field"><label for="email">E-mail *</label><input id="email" name="email" type="email" required autocomplete="email"><div class="error"></div></div><div class="field"><label for="phone">Telefone *</label><input id="phone" name="phone" required inputmode="tel" autocomplete="tel" placeholder="(11) 98765-4321"><div class="error"></div></div><div class="field"><label for="birth">Data de nascimento *</label><input id="birth" name="birth" type="date" required autocomplete="bday"><div class="error"></div></div><div class="actions"><button class="btn" type="submit">Enviar cadastro</button><button class="btn secondary" type="reset">Limpar</button></div></form></section>`
};